const GET_ERRORS = "GET_ERRORS";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const CLEAR_ERRORS = "CLEAR_ERRORS";
// profile
const GET_PROFILE = "GET_PROFILE";
const GET_PROFILES = "GET_PROFILES";
const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
const PROFILE_LOADING = "PROFILE_LOADING";

export {
  GET_ERRORS,
  SET_CURRENT_USER,
  CLEAR_ERRORS,
  GET_PROFILE,
  GET_PROFILES,
  CLEAR_CURRENT_PROFILE,
  PROFILE_NOT_FOUND,
  PROFILE_LOADING
};
